package ca.willatendo.fossilsclassic.server.item;

import ca.willatendo.fossilsclassic.core.utils.FCCoreUtils;
import ca.willatendo.fossilsclassic.server.block.FCBlocks;
import ca.willatendo.fossilsclassic.server.entity.FCEntityTypes;
import ca.willatendo.fossilsclassic.server.item.items.*;
import ca.willatendo.fossilsclassic.server.item.items.EggItem;
import ca.willatendo.simplelibrary.core.holder.SimpleHolder;
import ca.willatendo.simplelibrary.core.registry.sub.ItemSubRegistry;
import net.minecraft.core.component.DataComponents;
import net.minecraft.world.entity.Entity;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.entity.Mob;
import net.minecraft.world.item.*;
import net.minecraft.world.item.equipment.ArmorType;

import java.util.function.Supplier;

// Update when on next SL
public final class FCItems {
    public static final ItemSubRegistry ITEMS = new ItemSubRegistry(FCCoreUtils.ID);

    public static final SimpleHolder<BlockItem> FOSSIL_ORE = ITEMS.registerBlock(FCBlocks.FOSSIL_ORE);
    public static final SimpleHolder<BlockItem> DEEPSLATE_FOSSIL_ORE = ITEMS.registerBlock(FCBlocks.DEEPSLATE_FOSSIL_ORE);
    public static final SimpleHolder<BlockItem> SKULL_BLOCK = ITEMS.registerBlock(FCBlocks.SKULL_BLOCK);
    public static final SimpleHolder<BlockItem> SKULL_LANTERN_BLOCK = ITEMS.registerBlock(FCBlocks.SKULL_LANTERN_BLOCK);
    public static final SimpleHolder<BlockItem> ANALYZER = ITEMS.registerBlock(FCBlocks.ANALYZER);
    public static final SimpleHolder<BlockItem> CULTIVATOR = ITEMS.registerBlock(FCBlocks.CULTIVATOR);
    public static final SimpleHolder<BlockItem> ARCHAEOLOGY_WORKBENCH = ITEMS.registerBlock(FCBlocks.ARCHAEOLOGY_WORKBENCH);
    public static final SimpleHolder<BlockItem> JURASSIC_FERN = ITEMS.registerBlock(FCBlocks.JURASSIC_FERN);
    public static final SimpleHolder<BlockItem> DRUM = ITEMS.registerBlock(FCBlocks.DRUM);
    public static final SimpleHolder<BlockItem> FEEDER = ITEMS.registerBlock(FCBlocks.FEEDER);
    public static final SimpleHolder<BlockItem> PERMAFROST = ITEMS.registerBlock(FCBlocks.PERMAFROST);
    public static final SimpleHolder<BlockItem> ICED_STONE = ITEMS.registerBlock(FCBlocks.ICED_STONE);
    public static final SimpleHolder<PlaceOnWaterBlockItem> AXOLOTLSPAWN = ITEMS.registerBlock(FCBlocks.AXOLOTLSPAWN, PlaceOnWaterBlockItem::new);

    public static final SimpleHolder<FossilItem> FOSSIL = ITEMS.registerItem("fossil", FossilItem::new);
    public static final SimpleHolder<Item> TRICERATOPS_DNA = ITEMS.registerItem("triceratops_dna");
    public static final SimpleHolder<Item> VELOCIRAPTOR_DNA = ITEMS.registerItem("velociraptor_dna");
    public static final SimpleHolder<Item> TYRANNOSAURUS_DNA = ITEMS.registerItem("tyrannosaurus_dna");
    public static final SimpleHolder<Item> PTERANODON_DNA = ITEMS.registerItem("pteranodon_dna");
    public static final SimpleHolder<Item> NAUTILUS_DNA = ITEMS.registerItem("nautilus_dna");
    public static final SimpleHolder<Item> FUTABASAURUS_DNA = ITEMS.registerItem("futabasaurus_dna");
    public static final SimpleHolder<Item> MOSASAURUS_DNA = ITEMS.registerItem("mosasaurus_dna");
    public static final SimpleHolder<Item> STEGOSAURUS_DNA = ITEMS.registerItem("stegosaurus_dna");
    public static final SimpleHolder<Item> DILOPHOSAURUS_DNA = ITEMS.registerItem("dilophosaurus_dna");
    public static final SimpleHolder<Item> BRACHIOSAURUS_DNA = ITEMS.registerItem("brachiosaurus_dna");
    public static final SimpleHolder<EggItem> TRICERATOPS_EGG = ITEMS.registerItem("triceratops_egg", properties -> new EggItem(FCEntityTypes.TRICERATOPS_EGG::get, properties), () -> new Item.Properties().stacksTo(1));
    public static final SimpleHolder<EggItem> VELOCIRAPTOR_EGG = ITEMS.registerItem("velociraptor_egg", properties -> new EggItem(FCEntityTypes.VELOCIRAPTOR_EGG::get, properties), () -> new Item.Properties().stacksTo(1));
    public static final SimpleHolder<EggItem> TYRANNOSAURUS_EGG = ITEMS.registerItem("tyrannosaurus_egg", properties -> new EggItem(FCEntityTypes.TYRANNOSAURUS_EGG::get, properties), () -> new Item.Properties().stacksTo(1));
    public static final SimpleHolder<EggItem> PTERANODON_EGG = ITEMS.registerItem("pteranodon_egg", properties -> new EggItem(FCEntityTypes.PTERANODON_EGG::get, properties), () -> new Item.Properties().stacksTo(1));
    //public static final SimpleHolder<PlaceEntityItem<Nautilus>> NAUTILUS_EGGS = ITEMS.registerItem("nautilus_eggs", properties -> new PlaceEntityItem<>(() -> EntityType.NAUTILUS, properties), new Item.Properties().stacksTo(1));
    public static final SimpleHolder<EggItem> FUTABASAURUS_EGG = ITEMS.registerItem("futabasaurus_egg", properties -> new EggItem(FCEntityTypes.FUTABASAURUS_EGG::get, properties), () -> new Item.Properties().stacksTo(1));
    public static final SimpleHolder<EggItem> MOSASAURUS_EGG = ITEMS.registerItem("mosasaurus_egg", properties -> new EggItem(FCEntityTypes.MOSASAURUS_EGG::get, properties), () -> new Item.Properties().stacksTo(1));
    public static final SimpleHolder<EggItem> STEGOSAURUS_EGG = ITEMS.registerItem("stegosaurus_egg", properties -> new EggItem(FCEntityTypes.STEGOSAURUS_EGG::get, properties), () -> new Item.Properties().stacksTo(1));
    public static final SimpleHolder<EggItem> DILOPHOSAURUS_EGG = ITEMS.registerItem("dilophosaurus_egg", properties -> new EggItem(FCEntityTypes.DILOPHOSAURUS_EGG::get, properties), () -> new Item.Properties().stacksTo(1));
    public static final SimpleHolder<EggItem> BRACHIOSAURUS_EGG = ITEMS.registerItem("brachiosaurus_egg", properties -> new EggItem(FCEntityTypes.BRACHIOSAURUS_EGG::get, properties), () -> new Item.Properties().stacksTo(1));
    public static final SimpleHolder<Item> RAW_TRICERATOPS = ITEMS.registerItem("raw_triceratops", new Item.Properties().food(FCFoods.RAW_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> RAW_VELOCIRAPTOR = ITEMS.registerItem("raw_velociraptor", new Item.Properties().food(FCFoods.RAW_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> RAW_TYRANNOSAURUS = ITEMS.registerItem("raw_tyrannosaurus", new Item.Properties().food(FCFoods.RAW_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> RAW_PTERANODON = ITEMS.registerItem("raw_pteranodon", new Item.Properties().food(FCFoods.RAW_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> RAW_FUTABASAURUS = ITEMS.registerItem("raw_futabasaurus", new Item.Properties().food(FCFoods.RAW_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> RAW_MOSASAURUS = ITEMS.registerItem("raw_mosasaurus", new Item.Properties().food(FCFoods.RAW_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> RAW_STEGOSAURUS = ITEMS.registerItem("raw_stegosaurus", new Item.Properties().food(FCFoods.RAW_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> RAW_DILOPHOSAURUS = ITEMS.registerItem("raw_dilophosaurus", new Item.Properties().food(FCFoods.RAW_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> RAW_BRACHIOSAURUS = ITEMS.registerItem("raw_brachiosaurus", new Item.Properties().food(FCFoods.RAW_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> RAW_SMILODON = ITEMS.registerItem("raw_smilodon", new Item.Properties().food(FCFoods.RAW_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> RAW_MAMMOTH = ITEMS.registerItem("raw_mammoth", new Item.Properties().food(FCFoods.RAW_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> COOKED_TRICERATOPS = ITEMS.registerItem("cooked_triceratops", new Item.Properties().food(FCFoods.COOKED_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> COOKED_VELOCIRAPTOR = ITEMS.registerItem("cooked_velociraptor", new Item.Properties().food(FCFoods.COOKED_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> COOKED_TYRANNOSAURUS = ITEMS.registerItem("cooked_tyrannosaurus", new Item.Properties().food(FCFoods.COOKED_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> COOKED_PTERANODON = ITEMS.registerItem("cooked_pteranodon", new Item.Properties().food(FCFoods.COOKED_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> COOKED_FUTABASAURUS = ITEMS.registerItem("cooked_futabasaurus", new Item.Properties().food(FCFoods.COOKED_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> COOKED_MOSASAURUS = ITEMS.registerItem("cooked_mosasaurus", new Item.Properties().food(FCFoods.COOKED_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> COOKED_STEGOSAURUS = ITEMS.registerItem("cooked_stegosaurus", new Item.Properties().food(FCFoods.COOKED_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> COOKED_DILOPHOSAURUS = ITEMS.registerItem("cooked_dilophosaurus", new Item.Properties().food(FCFoods.COOKED_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> COOKED_BRACHIOSAURUS = ITEMS.registerItem("cooked_brachiosaurus", new Item.Properties().food(FCFoods.COOKED_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> COOKED_SMILODON = ITEMS.registerItem("cooked_smilodon", new Item.Properties().food(FCFoods.COOKED_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> COOKED_MAMMOTH = ITEMS.registerItem("cooked_mammoth", new Item.Properties().food(FCFoods.COOKED_DINOSAUR_MEAT));
    public static final SimpleHolder<Item> TYRANNOSAURUS_TOOTH = ITEMS.registerItem("tyrannosaurus_tooth");
    public static final SimpleHolder<ShearsItem> TOOTH_DAGGER = ITEMS.registerItem("tooth_dagger", ShearsItem::new, () -> new Item.Properties().sword(FCToolMaterials.DAGGER, 3, -2.4F).component(DataComponents.TOOL, ShearsItem.createToolProperties()));
    public static final SimpleHolder<Item> SKULL_STICK = ITEMS.registerItem("skull_stick", new Item.Properties().stacksTo(1));
    public static final SimpleHolder<DinopediaItem> DINOPEDIA = ITEMS.registerItem("dinopedia", DinopediaItem::new, new Item.Properties().stacksTo(1));
    public static final SimpleHolder<Item> RAW_CHICKEN_SOUP_BUCKET = ITEMS.registerItem("raw_chicken_soup_bucket", new Item.Properties().stacksTo(1).craftRemainder(Items.BUCKET).food(FCFoods.RAW_CHICKEN_SOUP, FCConsumables.RAW_CHICKEN_SOUP_BUCKET).usingConvertsTo(Items.BUCKET));
    public static final SimpleHolder<Item> COOKED_CHICKEN_SOUP_BUCKET = ITEMS.registerItem("cooked_chicken_soup_bucket", new Item.Properties().stacksTo(1).craftRemainder(Items.BUCKET).food(FCFoods.COOKED_CHICKEN_SOUP).usingConvertsTo(Items.BUCKET));
    public static final SimpleHolder<ChickenEssanceBottleItem> CHICKEN_ESSENCE_BOTTLE = ITEMS.registerItem("chicken_essence_bottle", ChickenEssanceBottleItem::new, new Item.Properties().stacksTo(16).food(FCFoods.CHICKEN_ESSENCE).usingConvertsTo(Items.BUCKET));
    public static final SimpleHolder<MagicConchItem> MAGIC_CONCH = ITEMS.registerItem("magic_conch", MagicConchItem::new, new Item.Properties().stacksTo(1));
    public static final SimpleHolder<FrozenMeatItem> FROZEN_MEAT = ITEMS.registerItem("frozen_meat", properties -> new FrozenMeatItem(FCToolMaterials.ICED_MEAT, 3.0F, -2.4F, FCItems.BROKEN_FROZEN_MEAT, properties), new Item.Properties());
    public static final SimpleHolder<Item> BROKEN_FROZEN_MEAT = ITEMS.registerItem("broken_frozen_meat", () -> new Item.Properties().sword(FCToolMaterials.ICED_MEAT, 3.0F, -2.4F));
    public static final SimpleHolder<Item> AXOLOTL_DNA = ITEMS.registerItem("axolotl_dna");
    public static final SimpleHolder<Item> CAT_DNA = ITEMS.registerItem("cat_dna");
    public static final SimpleHolder<Item> CHICKEN_DNA = ITEMS.registerItem("chicken_dna");
    public static final SimpleHolder<Item> COW_DNA = ITEMS.registerItem("cow_dna");
    public static final SimpleHolder<Item> DOLPHIN_DNA = ITEMS.registerItem("dolphin_dna");
    public static final SimpleHolder<Item> DONKEY_DNA = ITEMS.registerItem("donkey_dna");
    public static final SimpleHolder<Item> FOX_DNA = ITEMS.registerItem("fox_dna");
    public static final SimpleHolder<Item> FROG_DNA = ITEMS.registerItem("frog_dna");
    public static final SimpleHolder<Item> GOAT_DNA = ITEMS.registerItem("goat_dna");
    public static final SimpleHolder<Item> HORSE_DNA = ITEMS.registerItem("horse_dna");
    public static final SimpleHolder<Item> LLAMA_DNA = ITEMS.registerItem("llama_dna");
    public static final SimpleHolder<Item> MULE_DNA = ITEMS.registerItem("mule_dna");
    public static final SimpleHolder<Item> OCELOT_DNA = ITEMS.registerItem("ocelot_dna");
    public static final SimpleHolder<Item> PANDA_DNA = ITEMS.registerItem("panda_dna");
    public static final SimpleHolder<Item> PARROT_DNA = ITEMS.registerItem("parrot_dna");
    public static final SimpleHolder<Item> PIG_DNA = ITEMS.registerItem("pig_dna");
    public static final SimpleHolder<Item> POLAR_BEAR_DNA = ITEMS.registerItem("polar_bear_dna");
    public static final SimpleHolder<Item> RABBIT_DNA = ITEMS.registerItem("rabbit_dna");
    public static final SimpleHolder<Item> SHEEP_DNA = ITEMS.registerItem("sheep_dna");
    public static final SimpleHolder<Item> WOLF_DNA = ITEMS.registerItem("wolf_dna");
    public static final SimpleHolder<Item> SMILODON_DNA = ITEMS.registerItem("smilodon_dna");
    public static final SimpleHolder<Item> MAMMOTH_DNA = ITEMS.registerItem("mammoth_dna");
    public static final SimpleHolder<SyringeItem> ARMADILLO_EMBRYO_SYRINGE = FCItems.registerSyringe("armadillo_embryo_syringe", () -> EntityType.ARMADILLO);
    public static final SimpleHolder<SyringeItem> BAT_EMBRYO_SYRINGE = FCItems.registerSyringe("bat_embryo_syringe", () -> EntityType.BAT);
    public static final SimpleHolder<SyringeItem> CAT_EMBRYO_SYRINGE = FCItems.registerSyringe("cat_embryo_syringe", () -> EntityType.CAT);
    //public static final SimpleHolder<IncubatedEggItem> INCUBATED_CHICKEN_EGG = FCItems.registerSyringe("incubated_chicken_egg", properties -> new IncubatedEggItem(0, properties), new Item.Properties().stacksTo(16));
    public static final SimpleHolder<SyringeItem> CAMEL_EMBRYO_SYRINGE = FCItems.registerSyringe("camel_embryo_syringe", () -> EntityType.CAMEL);
    public static final SimpleHolder<SyringeItem> COW_EMBRYO_SYRINGE = FCItems.registerSyringe("cow_embryo_syringe", () -> EntityType.COW);
    public static final SimpleHolder<SyringeItem> DOLPHIN_EMBRYO_SYRINGE = FCItems.registerSyringe("dolphin_embryo_syringe", () -> EntityType.DOLPHIN);
    public static final SimpleHolder<SyringeItem> DONKEY_EMBRYO_SYRINGE = FCItems.registerSyringe("donkey_embryo_syringe", () -> EntityType.DONKEY);
    public static final SimpleHolder<SyringeItem> FOX_EMBRYO_SYRINGE = FCItems.registerSyringe("fox_embryo_syringe", () -> EntityType.FOX);
    public static final SimpleHolder<SyringeItem> GOAT_EMBRYO_SYRINGE = FCItems.registerSyringe("goat_embryo_syringe", () -> EntityType.GOAT);
    public static final SimpleHolder<SyringeItem> HORSE_EMBRYO_SYRINGE = FCItems.registerSyringe("horse_embryo_syringe", () -> EntityType.HORSE);
    public static final SimpleHolder<SyringeItem> LLAMA_EMBRYO_SYRINGE = FCItems.registerSyringe("llama_embryo_syringe", () -> EntityType.LLAMA);
    public static final SimpleHolder<SyringeItem> MULE_EMBRYO_SYRINGE = FCItems.registerSyringe("mule_embryo_syringe", () -> EntityType.MULE);
    public static final SimpleHolder<SyringeItem> OCELOT_EMBRYO_SYRINGE = FCItems.registerSyringe("ocelot_embryo_syringe", () -> EntityType.OCELOT);
    public static final SimpleHolder<SyringeItem> PANDA_EMBRYO_SYRINGE = FCItems.registerSyringe("panda_embryo_syringe", () -> EntityType.PANDA);
    //public static final SimpleHolder<IncubatedEggItem> INCUBATED_PARROT_EGG = FCItems.registerSyringe("incubated_parrot_egg", properties -> new IncubatedEggItem(1, properties), new Item.Properties().stacksTo(16));
    public static final SimpleHolder<SyringeItem> PIG_EMBRYO_SYRINGE = FCItems.registerSyringe("pig_embryo_syringe", () -> EntityType.PIG);
    public static final SimpleHolder<SyringeItem> POLAR_BEAR_EMBRYO_SYRINGE = FCItems.registerSyringe("polar_bear_embryo_syringe", () -> EntityType.POLAR_BEAR);
    public static final SimpleHolder<SyringeItem> RABBIT_EMBRYO_SYRINGE = FCItems.registerSyringe("rabbit_embryo_syringe", () -> EntityType.RABBIT);
    public static final SimpleHolder<SyringeItem> SHEEP_EMBRYO_SYRINGE = FCItems.registerSyringe("sheep_embryo_syringe", () -> EntityType.SHEEP);
    public static final SimpleHolder<SyringeItem> WOLF_EMBRYO_SYRINGE = FCItems.registerSyringe("wolf_embryo_syringe", () -> EntityType.WOLF);
    public static final SimpleHolder<SyringeItem> SMILODON_EMBRYO_SYRINGE = FCItems.registerSyringe("smilodon_embryo_syringe", () -> EntityType.SLIME);
    public static final SimpleHolder<SyringeItem> MAMMOTH_EMBRYO_SYRINGE = FCItems.registerSyringe("mammoth_embryo_syringe", () -> EntityType.SLIME);
    public static final SimpleHolder<Item> JURASSIC_FERN_SPORES = ITEMS.registerItem("jurassic_fern_spores", new Item.Properties());
    public static final SimpleHolder<Item> RELIC_SCRAP = ITEMS.registerItem("relic_scrap");
    public static final SimpleHolder<StoneTabletItem> STONE_TABLET = ITEMS.registerItem("stone_tablet", StoneTabletItem::new);
    public static final SimpleHolder<Item> BROKEN_ANCIENT_SWORD = ITEMS.registerItem("broken_ancient_sword");
    public static final SimpleHolder<Item> BROKEN_ANCIENT_HELMET = ITEMS.registerItem("broken_ancient_helmet");
    public static final SimpleHolder<Item> SCARAB_GEM = ITEMS.registerItem("scarab_gem");
    public static final SimpleHolder<AncientSwordItem> ANCIENT_SWORD = ITEMS.registerItem("ancient_sword", AncientSwordItem::new, () -> new Item.Properties().sword(FCToolMaterials.ANCIENT, 3.0F, -2.4F));
    public static final SimpleHolder<Item> ANCIENT_HELMET = ITEMS.registerItem("ancient_helmet", () -> new Item.Properties().humanoidArmor(FCArmorMaterial.ANCIENT, ArmorType.HELMET));
    public static final SimpleHolder<Item> SCARAB_GEM_SWORD = ITEMS.registerItem("scarab_gem_sword", () -> new Item.Properties().sword(FCToolMaterials.SCARAB_GEM, 3.0F, -2.4F));
    public static final SimpleHolder<ShovelItem> SCARAB_GEM_SHOVEL = ITEMS.registerItem("scarab_gem_shovel", properties -> new ShovelItem(FCToolMaterials.SCARAB_GEM, 1.5F, -3.0F, properties));
    public static final SimpleHolder<Item> SCARAB_GEM_PICKAXE = ITEMS.registerItem("scarab_gem_pickaxe", () -> new Item.Properties().pickaxe(FCToolMaterials.SCARAB_GEM, 1.0F, -2.8F));
    public static final SimpleHolder<AxeItem> SCARAB_GEM_AXE = ITEMS.registerItem("scarab_gem_axe", properties -> new AxeItem(FCToolMaterials.SCARAB_GEM, 5.0F, -3.0F, properties));
    public static final SimpleHolder<HoeItem> SCARAB_GEM_HOE = ITEMS.registerItem("scarab_gem_hoe", properties -> new HoeItem(FCToolMaterials.SCARAB_GEM, -4.0F, 0.0F, properties));
    public static final SimpleHolder<ModSmithingTemplateItem> SCARAB_GEM_UPGRADE_SMITHING_TEMPLATE = ITEMS.registerItem("scarab_gem_upgrade_smithing_template", ModSmithingTemplateItem::createGemUpgradeTemplate, new Item.Properties().rarity(Rarity.UNCOMMON));
    public static final SimpleHolder<JavelinItem> WOODEN_JAVELIN = ITEMS.registerItem("wooden_javelin", properties -> new JavelinItem(ToolMaterial.WOOD, FCItems.BROKEN_WOODEN_JAVELIN::get, FCEntityTypes.THROWN_WOODEN_JAVELIN::get, properties), new Item.Properties());
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_WOODEN_JAVELIN = ITEMS.registerItem("broken_wooden_javelin", properties -> new BrokenJavelinItem(ToolMaterial.WOOD, FCEntityTypes.THROWN_WOODEN_JAVELIN::get, properties), new Item.Properties());
    public static final SimpleHolder<JavelinItem> STONE_JAVELIN = ITEMS.registerItem("stone_javelin", properties -> new JavelinItem(ToolMaterial.STONE, FCItems.BROKEN_STONE_JAVELIN::get, FCEntityTypes.THROWN_STONE_JAVELIN::get, properties), new Item.Properties());
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_STONE_JAVELIN = ITEMS.registerItem("broken_stone_javelin", properties -> new BrokenJavelinItem(ToolMaterial.STONE, FCEntityTypes.THROWN_STONE_JAVELIN::get, properties), new Item.Properties());
    public static final SimpleHolder<JavelinItem> COPPER_JAVELIN = ITEMS.registerItem("copper_javelin", properties -> new JavelinItem(ToolMaterial.COPPER, FCItems.BROKEN_COPPER_JAVELIN::get, FCEntityTypes.THROWN_COPPER_JAVELIN::get, properties), new Item.Properties());
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_COPPER_JAVELIN = ITEMS.registerItem("broken_copper_javelin", properties -> new BrokenJavelinItem(ToolMaterial.COPPER, FCEntityTypes.THROWN_COPPER_JAVELIN::get, properties), new Item.Properties());
    public static final SimpleHolder<JavelinItem> IRON_JAVELIN = ITEMS.registerItem("iron_javelin", properties -> new JavelinItem(ToolMaterial.IRON, FCItems.BROKEN_IRON_JAVELIN::get, FCEntityTypes.THROWN_IRON_JAVELIN::get, properties), new Item.Properties());
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_IRON_JAVELIN = ITEMS.registerItem("broken_iron_javelin", properties -> new BrokenJavelinItem(ToolMaterial.IRON, FCEntityTypes.THROWN_IRON_JAVELIN::get, properties), new Item.Properties());
    public static final SimpleHolder<JavelinItem> GOLDEN_JAVELIN = ITEMS.registerItem("golden_javelin", properties -> new JavelinItem(ToolMaterial.GOLD, FCItems.BROKEN_GOLDEN_JAVELIN::get, FCEntityTypes.THROWN_GOLDEN_JAVELIN::get, properties), new Item.Properties());
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_GOLDEN_JAVELIN = ITEMS.registerItem("broken_golden_javelin", properties -> new BrokenJavelinItem(ToolMaterial.GOLD, FCEntityTypes.THROWN_GOLDEN_JAVELIN::get, properties), new Item.Properties());
    public static final SimpleHolder<JavelinItem> DIAMOND_JAVELIN = ITEMS.registerItem("diamond_javelin", properties -> new JavelinItem(ToolMaterial.DIAMOND, FCItems.BROKEN_DIAMOND_JAVELIN::get, FCEntityTypes.THROWN_DIAMOND_JAVELIN::get, properties), new Item.Properties());
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_DIAMOND_JAVELIN = ITEMS.registerItem("broken_diamond_javelin", properties -> new BrokenJavelinItem(ToolMaterial.DIAMOND, FCEntityTypes.THROWN_DIAMOND_JAVELIN::get, properties), new Item.Properties());
    public static final SimpleHolder<JavelinItem> NETHERITE_JAVELIN = ITEMS.registerItem("netherite_javelin", properties -> new JavelinItem(ToolMaterial.NETHERITE, FCItems.BROKEN_NETHERITE_JAVELIN::get, FCEntityTypes.THROWN_NETHERITE_JAVELIN::get, properties), new Item.Properties());
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_NETHERITE_JAVELIN = ITEMS.registerItem("broken_netherite_javelin", properties -> new BrokenJavelinItem(ToolMaterial.NETHERITE, FCEntityTypes.THROWN_NETHERITE_JAVELIN::get, properties), new Item.Properties());
    public static final SimpleHolder<JavelinItem> SCARAB_GEM_JAVELIN = ITEMS.registerItem("scarab_gem_javelin", properties -> new JavelinItem(FCToolMaterials.SCARAB_GEM, FCItems.BROKEN_SCARAB_GEM_JAVELIN::get, FCEntityTypes.THROWN_SCARAB_GEM_JAVELIN::get, true, properties), new Item.Properties());
    public static final SimpleHolder<BrokenJavelinItem> BROKEN_SCARAB_GEM_JAVELIN = ITEMS.registerItem("broken_scarab_gem_javelin", properties -> new BrokenJavelinItem(FCToolMaterials.SCARAB_GEM, FCEntityTypes.THROWN_SCARAB_GEM_JAVELIN::get, true, properties), new Item.Properties());
    //public static final SimpleHolder<SpawnEggItem> ANU_SPAWN_EGG = ITEMS.registerItem("anu_spawn_egg", () -> new SpawnEggItem(FossilsLegacyEntityTypes.ANU.get(), 0x432600, 0xa62c14, new Item.Properties()));
    public static final SimpleHolder<SpawnEggItem> BONES_SPAWN_EGG = FCItems.registerSpawnEgg("bones_spawn_egg", FCEntityTypes.BONES);
    public static final SimpleHolder<SpawnEggItem> FAILURESAURUS_SPAWN_EGG = FCItems.registerSpawnEgg("failuresaurus_spawn_egg", FCEntityTypes.FAILURESAURUS);
    /*public static final SimpleHolder<DinosaurSpawnEggItem> BRACHIOSAURUS_SPAWN_EGG = ITEMS.registerItem("brachiosaurus_spawn_egg", () -> new DinosaurSpawnEggItem(FossilsLegacyEntityTypes.BRACHIOSAURUS.get(), 0x3b3e55, 0x7f8ba1, new Item.Properties()));
    public static final SimpleHolder<DinosaurSpawnEggItem> DILOPHOSAURUS_SPAWN_EGG = ITEMS.registerItem("dilophosaurus_spawn_egg", () -> new DinosaurSpawnEggItem(FossilsLegacyEntityTypes.DILOPHOSAURUS.get(), 0x686442, 0xf1bc2c, new Item.Properties()));
    public static final SimpleHolder<DinosaurSpawnEggItem> FUTABASAURUS_SPAWN_EGG = ITEMS.registerItem("futabasaurus_spawn_egg", () -> new DinosaurSpawnEggItem(FossilsLegacyEntityTypes.FUTABASAURUS.get(), 0xca6700, 0xb92200, new Item.Properties()));
    public static final SimpleHolder<DinosaurSpawnEggItem> MAMMOTH_SPAWN_EGG = ITEMS.registerItem("mammoth_spawn_egg", () -> new DinosaurSpawnEggItem(FossilsLegacyEntityTypes.MAMMOTH.get(), 0x3d2700, 0x211500, new Item.Properties()));
    public static final SimpleHolder<DinosaurSpawnEggItem> MOSASAURUS_SPAWN_EGG = ITEMS.registerItem("mosasaurus_spawn_egg", () -> new DinosaurSpawnEggItem(FossilsLegacyEntityTypes.MOSASAURUS.get(), 0x0d7346, 0xffe1a7, new Item.Properties()));
    public static final SimpleHolder<SpawnEggItem> NAUTILUS_SPAWN_EGG = ITEMS.registerItem("nautilus_spawn_egg", () -> new SpawnEggItem(FossilsLegacyEntityTypes.NAUTILUS.get(), 0xc1c1c1, 0xa95453, new Item.Properties()));
    public static final SimpleHolder<DinosaurSpawnEggItem> PTERANODON_SPAWN_EGG = ITEMS.registerItem("pteranodon_spawn_egg", () -> new DinosaurSpawnEggItem(FossilsLegacyEntityTypes.PTERANODON.get(), 0x7c5d89, 0x450e5b, new Item.Properties()));
    public static final SimpleHolder<DinosaurSpawnEggItem> SMILODON_SPAWN_EGG = ITEMS.registerItem("smilodon_spawn_egg", () -> new DinosaurSpawnEggItem(FossilsLegacyEntityTypes.SMILODON.get(), 0xefa745, 0x9a6527, new Item.Properties()));
    public static final SimpleHolder<DinosaurSpawnEggItem> STEGOSAURUS_SPAWN_EGG = ITEMS.registerItem("stegosaurus_spawn_egg", () -> new DinosaurSpawnEggItem(FossilsLegacyEntityTypes.STEGOSAURUS.get(), 0x839d00, 0x785f00, new Item.Properties()));
    */
    public static final SimpleHolder<SpawnEggItem> TRICERATOPS_SPAWN_EGG = FCItems.registerSpawnEgg("triceratops_spawn_egg", FCEntityTypes.TRICERATOPS);
    /*public static final SimpleHolder<DinosaurSpawnEggItem> TYRANNOSAURUS_SPAWN_EGG = ITEMS.registerItem("tyrannosaurus_spawn_egg", () -> new DinosaurSpawnEggItem(FossilsLegacyEntityTypes.TYRANNOSAURUS.get(), 0x918066, 0x4f473a, new Item.Properties()));
    public static final SimpleHolder<DinosaurSpawnEggItem> VELOCIRAPTOR_SPAWN_EGG = ITEMS.registerItem("velociraptor_spawn_egg", () -> new DinosaurSpawnEggItem(FossilsLegacyEntityTypes.VELOCIRAPTOR.get(), 0x66965f, 0x884c2e, new Item.Properties()));*/

    public static final SimpleHolder<CustomSpawnEggItem> CUSTOM_SPAWN_EGG = ITEMS.registerItem("custom_spawn_egg", CustomSpawnEggItem::new);

    private static <T extends Entity> SimpleHolder<SpawnEggItem> registerSpawnEgg(String name, SimpleHolder<EntityType<T>> entityType) {
        return ITEMS.registerItem(name, SpawnEggItem::new, () -> new Item.Properties().spawnEgg(entityType.get()));
    }

    private static <T extends Mob> SimpleHolder<SyringeItem> registerSyringe(String name, Supplier<EntityType<T>> entityType) {
        return ITEMS.registerItem(name, SyringeItem::new, () -> new Item.Properties().spawnEgg(entityType.get()));
    }
}
